# docs: https://github.com/glanceapp/glance/blob/main/docs/configuration.md
# icons: https://simpleicons.org/
#
# to test the configuration:
#   docker run --rm -v $(pwd):/app/config -p 8080:8080/tcp glanceapp/glance:latest # http://127.0.0.1:8080/

pages:
  - name: Home
    hide-desktop-navigation: true
    center-vertically: true
    columns:
      - size: small
        widgets:
          - type: clock
            title: /now/time
            hide-header: true
            hour-format: 12h
            timezones: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
              - timezone: Poland
                label: Poland
              - timezone: Asia/Yekaterinburg
                label: Yekaterinburg
              - timezone: America/Denver
                label: USA (most areas)
          - type: bookmarks
            title: /bookmarks
            hide-header: true
            groups:
              - links:
                - title: /google/gmail
                  icon: si:gmail
                  hide-arrow: true
                  url: https://mail.google.com/mail/u/0/#inbox
                - title: /google/calendar
                  icon: si:googlecalendar
                  hide-arrow: true
                  url: https://calendar.google.com/calendar/u/0/r/month
                - title: /github/me
                  icon: si:github
                  hide-arrow: true
                  url: https://github.com/tarampampam?tab=repositories
                - title: /github/iddqd
                  icon: si:github
                  hide-arrow: true
                  url: https://github.com/iddqd-uk
                - title: /youtube
                  icon: si:youtube
                  hide-arrow: true
                  url: https://www.youtube.com/feed/subscriptions
                - title: /habr/go
                  icon: si:habr
                  hide-arrow: true
                  url: https://habr.com/en/hubs/go/articles/
              - title: work
                color: 40 70 50
                links:
                  - title: /ss/time-tracking
                    icon: si:jirasoftware
                    hide-arrow: true
                    url: https://jira.spiralscout.com/secure/Tempo.jspa#/my-work
                  - title: /gc/jira-board
                    icon: si:jira
                    hide-arrow: true
                    url: https://goconsensus.atlassian.net/jira/software/c/projects/CNS/boards/48
                  - title: /gc/gitlab
                    icon: si:gitlab
                    hide-arrow: true
                    url: https://gitlab.com/goconsensus/vets

      - size: full
        widgets:
          - type: search
            title: /search
            hide-header: true
            search-engine: duckduckgo
            autofocus: true
          - type: group
            widgets:
              - type: rss
                title: /go/rss
                style: horizontal-cards
                feeds:
                  - url: https://go.dev/blog/feed.atom?format=xml
                    title: The Go Blog
                  - url: https://habr.com/ru/rss/hub/go/all/?fl=ru
                    title: Habr/Go
              #- type: reddit
              #  style: horizontal-cards
              #  subreddit: golang
              - type: rss
                title: /go/releases
                style: vertical-list
                feeds: [{url: https://github.com/golang/go/releases.atom, title: Go releases}]
                collapse-after: 3
                single-line-titles: true

          - type: videos
            title: /videos/youtube
            hide-header: true
            channels:
              - UC4omkhNHsYLagT1o6hnmKQw # Winderton
              - UCUSbYJK87rpBUJ5KGQd7oHA # Мы обречены
              - UCe_TcJarfs-HKy3NySy8Kng # S0ER
              - UCeObZv89Stb2xLtjLJ0De3Q # ITBeard
              - UCJ8AJ0qd2-gk90OujUETzCg # ДЕПЛОЙ
              - UCnxk5BzZxRN7y3a1IqHhVlA # Pingvinus

      - size: small
        widgets:
          - type: calendar
            title: /now/date
            hide-header: true
          - type: weather
            title: /outside/weather
            hide-header: true
            hour-format: 12h
            location: Tbilisi, Georgia
            hide-location: true
          - type: markets
            hide-header: true
            markets:
              - symbol: RUB=X
                name: $/₽
                chart-link: https://www.google.com/search?q=USD%2FRUB+converter
theme:
  background-color: 0 0 17
  primary-color: 60 5 100

branding:
  hide-footer: true
  favicon-url: https://gravatar.com/avatar/68ac3bd2a8358568ab3382d7d8dbe35b?size=256

auth:
  secret-key: sp4Kw3goKmuGzvz3lo5hw9D5cZigemodOutJdRz/yhURaCIvW/bDHuqdnNpEAS+caz+XEZa/4G1337Xc+N1P9g== #gitleaks:allow
  users:
    kot:
      password-hash: $2a$10$2vJgUlCMpMOkbZ4f8HEZfeHyhtkL.E648ODPWBx/YXqdFG60fe7ke
