{{ with .Values.httpProxy }}
{{- if $.Values.doppler.enabled }}

{{- include "doppler.resourcesToFetchSecrets" (dict
  "dopplerServiceToken" $.Values.doppler.serviceToken
  "namespace" .namespaceOverride
  "appName" .nameOverride
  "secretNames" (tuple
    $.Values.doppler.secrets.httpProxyLogin
    $.Values.doppler.secrets.httpProxyPassword
  )
) }}

{{- end }}
{{- end }}

