{{ with .Values.httpProxy }}
{{- if .enabled }}
apiVersion: v1
kind: Service

metadata:
  name: {{ .appName }}-service
  namespace: {{ .namespace }}
  labels: {app: "{{ .appName }}"}

spec:
  type: ClusterIP
  selector: {app: "{{ .appName }}"}
  ports:
    - name: "http-proxy"
      protocol: TCP
      port: 3128
      targetPort: 3128
{{- end }}
{{- end }}
