{{- if .Values.httpProxy.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP

metadata:
  name: {{ .Values.httpProxy.appName }}-http-tcp-ingress
  namespace: {{ .Values.namespace }}

spec:
  entryPoints: [3proxy-http] # the name defined in the values.yaml
  routes:
    - match: HostSNI(`*`)
      services: [{name: "{{ .Values.httpProxy.appName }}-service", namespace: {{ .Values.namespace }}, port: 3128}]
{{- end }}
