{{ with .Values.tgRssBot }}
{{- if .enabled }}
{{- if $.Values.doppler.enabled }}

{{- include "doppler.resourcesToFetchSecrets" (dict
  "dopplerServiceToken" $.Values.doppler.serviceToken
  "namespace" .namespace
  "appName" .appName
  "secretNames" (tuple
    $.Values.doppler.secrets.tgRssBotAuthToken
    $.Values.doppler.secrets.tgRssBotAdminID
  )
) }}

{{- end }}
{{- end }}
{{- end }}
