{{ with .Values.tgProxy }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .appName }}
  namespace: {{ .namespace }}
  labels: {app: "{{ .appName }}"}

spec:
  replicas: {{ $.Values.tgProxy.replicaCount | default 1 }}
  selector: {matchLabels: {app: "{{ .appName }}"}}
  template:
    metadata: {labels: {app: "{{ .appName }}"}}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: "{{ .appName }}"
          image: "ghcr.io/9seconds/mtg:{{ .version | default "2" }}"
          args:
            - simple-run
            - 0.0.0.0:443
            - $(TG_SECRET)
            #- --debug
            - --concurrency=512
            - --prefer-ip=prefer-ipv4
            - --domain-fronting-port=443
            - --doh-ip=9.9.9.9
            - --antireplay-cache-size=1MB
          env:
            - name: TG_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .appName }}-secrets"
                  key: {{ $.Values.doppler.secrets.tgProxySecret }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
          ports:
            - {name: tg-proxy-port, containerPort: 443, protocol: TCP}
          livenessProbe:
            tcpSocket: {port: 443}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket: {port: 443}
            periodSeconds: 10
          resources:
            requests: {memory: 256Mi, cpu: 200m}
            limits: {memory: 512Mi, cpu: 550m}
      affinity:
        nodeAffinity:
          {{- toYaml $.Values.common.preferWorkersButAllowMaster | nindent 10 }}
{{- end }}
{{- end }}
