{{ with .Values.tgProxy }}
{{- if .enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP

metadata:
  name: {{ .appName }}-http-tcp-ingress
  namespace: {{ .namespace }}

spec: # https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroutetcp
  entryPoints: [websecure]
  routes:
    - match: "HostSNI(`{{ .domainName }}`)"
      services: [{name: "{{ .appName }}-service", namespace: {{ .namespace }}, port: 443}]
  tls: {passthrough: true}
{{- end }}
{{- end }}
