{{- if .Values.tgProxy.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP

metadata:
  name: {{ .Values.tgProxy.appName }}-http-tcp-ingress
  namespace: {{ .Values.namespace }}

spec: # https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroutetcp
  entryPoints: [websecure]
  routes:
    - match: HostSNI(`ww2.iddqd.uk`) # You need to regenerate the secret whenever the domain name is changed!
      services: [{name: "{{ .Values.tgProxy.appName }}-service", namespace: {{ .Values.namespace }}, port: 443}]
  tls: {passthrough: true}
{{- end }}
