{{ with .Values.tgVideoDownloaderBot }}
{{- if $.Values.doppler.enabled }}

{{- include "doppler.resourcesToFetchSecrets" (dict
  "dopplerServiceToken" $.Values.doppler.serviceToken
  "namespace" .namespaceOverride
  "appName" .nameOverride
  "secretNames" (tuple
    $.Values.doppler.secrets.tgVideoDownloaderBotAuthToken
    $.Values.doppler.secrets.tgVideoDownloaderBotCookiesFile
  )
) }}

{{- end }}
{{- end }}
