{{ with .Values.kubeIddqd }}
{{- if .enabled }}

apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .appName }}-nginx-content
  namespace: {{ .namespace }}

data:
  index.html: |
    {{- $.Files.Get "files/kube-iddqd/index.html" | nindent 4 -}}

{{- end }}
{{- end }}
