{{ with .Values.kubeIddqd }}
{{- if .enabled }}
apiVersion: v1
kind: Service

metadata:
  name: {{ .appName }}-service
  namespace: {{ .namespace }}
  labels: {app: "{{ .appName }}"}

spec:
  type: ClusterIP
  selector: {app: "{{ .appName }}"}
  ports:
    - name: "http"
      protocol: TCP
      port: 8080
      targetPort: 8080
{{- end }}
{{- end }}
