{{ with .Values.kubeIddqd }}
{{- if .enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute

metadata:
  name: {{ .appName }}-http
  namespace: {{ .namespace }}

spec: # https://doc.traefik.io/traefik/routing/providers/kubernetes-crd/#kind-ingressroute
  entryPoints: [websecure]
  routes:
    - match: Host(`kube.iddqd.uk`) && PathPrefix(`/`)
      services: [{name: "{{ .appName }}-service", namespace: {{ .namespace }}, port: 8080}]
{{- end }}
{{- end }}
