{{ with .Values.errorPages }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment

metadata:
  name: "{{ .appName }}"
  namespace: {{ .namespace }}
  labels: {app: "{{ .appName }}"}

spec:
  replicas: 1
  selector: {matchLabels: {app: "{{ .appName }}"}}
  template:
    metadata: {labels: {app: "{{ .appName }}"}}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: "{{ .appName }}"
          image: "ghcr.io/tarampampam/error-pages:{{ .version | default "latest" }}"
          env:
            - {name: TEMPLATE_NAME, value: "{{ .themeName | default "app-down" }}"}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
          ports:
            - {name: http, containerPort: 8080, protocol: TCP}
          livenessProbe:
            httpGet: {port: http, path: /healthz}
            periodSeconds: 10
          readinessProbe:
            httpGet: {port: http, path: /healthz}
            periodSeconds: 10
          resources:
            limits: {memory: 64Mi, cpu: 200m}
            requests: {memory: 16Mi, cpu: 20m}
{{- end }}
{{- end }}
