{{ with .Values.miroTalk }}
{{- if .enabled }}
{{- if $.Values.doppler.enabled }}

{{- include "doppler.resourcesToFetchSecrets" (dict
  "dopplerServiceToken" $.Values.doppler.serviceToken
  "namespace" .namespace
  "appName" .appName
  "secretNames" (tuple
    $.Values.doppler.secrets.miroTalkJwtKey
    $.Values.doppler.secrets.miroTalkApiKeySecret
  )
) }}

{{- end }}
{{- end }}
{{- end }}
