{{ with .Values.miroTalk }}
{{- if .enabled }}

apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .appName }}
  namespace: {{ .namespace }}
  labels: {app: "{{ .appName }}"}

spec:
  replicas: 1
  selector: {matchLabels: {app: "{{ .appName }}"}}
  template:
    metadata:
      labels: {app: "{{ .appName }}"}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: "{{ .appName }}"
          image: "{{ .image }}:{{ .tag | default "latest" }}"
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
          env:
            - name: PORT
              value: '8080'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ .appName }}-secrets"
                  key: {{ $.Values.doppler.secrets.miroTalkJwtKey }}
            - name: API_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .appName }}-secrets"
                  key: {{ $.Values.doppler.secrets.miroTalkApiKeySecret}}
          ports:
            - {name: http, containerPort: 8080, protocol: TCP}
          livenessProbe:
            httpGet: {port: http, path: /stats}
            periodSeconds: 10
          readinessProbe:
            httpGet: {port: http, path: /stats}
            periodSeconds: 10
          resources:
            limits: {memory: 128Mi, cpu: 200m}
            requests: {memory: 32Mi, cpu: 20m}
      affinity:
        nodeAffinity:
          {{- toYaml $.Values.common.preferWorkersButAllowMaster | nindent 10 }}
{{- end }}
{{- end }}
