{{- if $.Values.doppler.enabled }}

{{- include "doppler.resourcesToFetchSecrets" (dict
  "dopplerServiceToken" $.Values.doppler.serviceToken
  "namespace" "monitoring"
  "appName" "monitoring"
  "secretNames" (tuple
    $.Values.doppler.secrets.newRelicLicenseKey
  )
) }}

{{- end }}
