{{- if .Values.doppler.enabled }}
{{- range $namespace := .Values.namespaces }}
---
{{/*
Create a secret with the Doppler token (it required for the external-secrets.io provider) in each namespace.
*/}}
apiVersion: v1
kind: Secret

metadata:
  name: {{ template "doppler.secretName" }}
  namespace: {{ $namespace }}

type: Opaque
data: {"{{ template "doppler.secretKeyName" }}": "{{ $.Values.doppler.serviceToken | b64enc }}"}
{{- end }}
{{- end }}
