# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: 🧪 Tests

on:
  workflow_dispatch: {}
  push:
    branches: [master, main]
    paths-ignore: ['**.md']
    tags-ignore: ['**']
  pull_request:
    paths-ignore: ['**.md']

concurrency:
  group: ${{ github.ref }}-tests
  cancel-in-progress: true

jobs:
  git-leaks:
    name: Check for GitLeaks
    runs-on: ubuntu-latest
    steps:
      - {uses: actions/checkout@v4, with: {fetch-depth: 0}}
      - uses: gacts/gitleaks@v1

  lint-charts:
    name: Lint the charts
    runs-on: ubuntu-latest
    strategy: {fail-fast: false, matrix: {chart: [apps, system]}}
    defaults: {run: {working-directory: "./helm/${{ matrix.chart }}"}}
    steps:
      - uses: actions/checkout@v4
      - uses: dopplerhq/cli-action@v3
      - uses: azure/setup-helm@v4
      - run: helm dependency update .
      - run: doppler --no-check-version secrets substitute ./values.doppler.yaml > ./values.yaml
        env: {DOPPLER_TOKEN: "${{ secrets.DOPPLER_SERVICE_TOKEN }}"}
      - run: helm template . > /dev/null
      - run: helm lint --strict .
      - uses: stackrox/kube-linter-action@v1
        with: {directory: .}
      - run: rm -f ./values.yaml
